// import PDFDocument from "pdfkit";
// import QRCode from "qrcode";
// import fs from "fs";
// import path from "path";
// import { fileURLToPath } from "url";

// // For __dirname replacement
// const __filename = fileURLToPath(import.meta.url);
// const __dirname = path.dirname(__filename);

// export async function generateSlip(loanData, res) {
//     // return new Promise(async (resolve, reject) => {
//     try {
//         const qrCodeDataURL = await QRCode.toDataURL(JSON.stringify(loanData));
//         // const { name, event, date, id } = data;

//         const doc = new PDFDocument();
//         res.setHeader('Content-Type', 'application/pdf');
//         res.setHeader('Content-Disposition', 'inline; filename=loan-slip.pdf');
//         doc.pipe(res);
//         // const filePath = path.join(__dirname, `../slips/${id}.pdf`);
//         // const stream = fs.createWriteStream(filePath);
//         // console.log(stream, "stream is here ");

//         // doc.pipe(stream);

//         // Heading
//         // doc
//         //     .fontSize(18)
//         //     .text("Event Participation Slip", { align: "center" })
//         //     .moveDown();

//         // // Data
//         // doc.fontSize(12).text(`Name: ${name}`);
//         // doc.text(`Event: ${event}`);
//         // doc.text(`Date: ${date}`);
//         doc.fontSize(20).text('Loan Slip', { align: 'center' });
//         doc.moveDown();
//         doc.fontSize(12).text(`Name: ${loanData.name}`);
//         doc.text(`Amount: ${loanData.amount}`);
//         doc.text(`Date: ${loanData.date}`);
//         doc.text(`Loan ID: ${loanData._id}`);

//         // QR Code
//         const qrData = `https://next-application-pi.vercel.app/home`;
//         const qrImageBuffer = await QRCode.toBuffer(qrData); // ✅
//         console.log(qrImageBuffer, "Image Buffer is here ");
//         // doc.image(qrImageBuffer, { fit: [150, 150], align: "center" });
//         doc.image(qrCodeDataURL, { fit: [150, 150], align: "center" });

//         // doc.text("Scan to verify", { align: "center" });

//         doc.end();

//         stream.on("finish", () => {
//             resolve(filePath);
//         });
//     } catch (error) {
//         reject(error);
//     }
//     // });
// }

import PDFDocument from "pdfkit";
import QRCode from "qrcode";

export async function generateSlip(loanData, res) {
  try {
    const qrData = `https://next-application-pi.vercel.app/loan/${loanData._id}`; // Better QR destination
    const qrImageBuffer = await QRCode.toBuffer(qrData);

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=loan-slip.pdf");

    doc.pipe(res);

    // 🔹 Title
    doc
      .fontSize(22)
      .fillColor("#333")
      .text("📄 Loan Slip", { align: "center", underline: true });
    doc.moveDown(2);

    // 🔹 Helper function for label-value styling
    const addField = (label, value) => {
      doc
        .font("Helvetica-Bold")
        .fontSize(12)
        .fillColor("#000")
        .text(`${label}:`, { continued: true })
        .font("Helvetica")
        .fillColor("#444")
        .text(` ${value}`);
    };

    // 🔹 Loan Fields (Styled)
    addField("User ID", loanData.userId);
    addField("Category", loanData.category);
    addField("Subcategory", loanData.subcategory);
    addField("Loan Amount", `Rs. ${loanData.loanAmount}`);
    addField("Loan Period", `${loanData.loanPeriod} months`);
    addField("Status", loanData.status);
    addField("Loan ID", loanData._id);
    addField("Created At", new Date(loanData.createdAt).toLocaleDateString());

    // 🔹 Separator Line
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke("#cccccc");
    doc.moveDown(2);

    // 🔹 QR Code Section
    doc
      .fontSize(14)
      .fillColor("#333")
      .text("Scan the QR code to view this slip online:", { align: "center" });
    doc.moveDown();
    doc.image(qrImageBuffer, doc.page.width / 2 - 75, doc.y + 10, {
      fit: [150, 150],
      align: "center",
    });

    // 🔹 Footer
    doc
      .moveDown(12)
      .fontSize(10)
      .fillColor("#888")
      .text("Generated by Loan Management System", { align: "center" });

    doc.end();
  } catch (error) {
    console.error("Error generating PDF:", error);
    res.status(500).send("Error generating PDF");
  }
}
